-- Phase 4: Standardize CMS/marketing enum VALUES to English (models/fields unchanged).
-- Pure enum value renames only — no table or column renames in this migration.

ALTER TYPE "TestimonialType" RENAME VALUE 'ORANG_TUA' TO 'PARENT';
ALTER TYPE "TestimonialType" RENAME VALUE 'GURU' TO 'TEACHER';
ALTER TYPE "TestimonialType" RENAME VALUE 'MITRA' TO 'PARTNER';

ALTER TYPE "MedalType" RENAME VALUE 'JUARA_1' TO 'FIRST_PLACE';
ALTER TYPE "MedalType" RENAME VALUE 'JUARA_2' TO 'SECOND_PLACE';
ALTER TYPE "MedalType" RENAME VALUE 'JUARA_3' TO 'THIRD_PLACE';
ALTER TYPE "MedalType" RENAME VALUE 'HARAPAN_1' TO 'HONORABLE_MENTION_1';
ALTER TYPE "MedalType" RENAME VALUE 'HARAPAN_2' TO 'HONORABLE_MENTION_2';
ALTER TYPE "MedalType" RENAME VALUE 'HARAPAN_3' TO 'HONORABLE_MENTION_3';

ALTER TYPE "AchievementLevel" RENAME VALUE 'INTERNASIONAL' TO 'INTERNATIONAL';
ALTER TYPE "AchievementLevel" RENAME VALUE 'NASIONAL' TO 'NATIONAL';
ALTER TYPE "AchievementLevel" RENAME VALUE 'PROVINSI' TO 'PROVINCE';
ALTER TYPE "AchievementLevel" RENAME VALUE 'KOTA' TO 'CITY';
ALTER TYPE "AchievementLevel" RENAME VALUE 'KECAMATAN' TO 'DISTRICT';
ALTER TYPE "AchievementLevel" RENAME VALUE 'SEKOLAH' TO 'SCHOOL';

ALTER TYPE "GalleryCategory" RENAME VALUE 'FASILITAS' TO 'FACILITIES';
ALTER TYPE "GalleryCategory" RENAME VALUE 'KEGIATAN' TO 'ACTIVITIES';
ALTER TYPE "GalleryCategory" RENAME VALUE 'PRESTASI' TO 'ACHIEVEMENTS';
ALTER TYPE "GalleryCategory" RENAME VALUE 'EKSKUL' TO 'EXTRACURRICULAR';
ALTER TYPE "GalleryCategory" RENAME VALUE 'LAINNYA' TO 'OTHER';

ALTER TYPE "EkskulCategory" RENAME VALUE 'ORGANISASI' TO 'ORGANIZATION';
ALTER TYPE "EkskulCategory" RENAME VALUE 'KEPANDUAN' TO 'SCOUTING';
ALTER TYPE "EkskulCategory" RENAME VALUE 'BELADIRI' TO 'MARTIAL_ARTS';
ALTER TYPE "EkskulCategory" RENAME VALUE 'OLAHRAGA' TO 'SPORTS';
ALTER TYPE "EkskulCategory" RENAME VALUE 'SENI' TO 'ARTS';
ALTER TYPE "EkskulCategory" RENAME VALUE 'AKADEMIK' TO 'ACADEMIC';
ALTER TYPE "EkskulCategory" RENAME VALUE 'KEAGAMAAN' TO 'RELIGIOUS';
ALTER TYPE "EkskulCategory" RENAME VALUE 'LAINNYA' TO 'OTHER';
